### ISSUE TITLE
Support thrift master?

### ISSUE THREAD

**Issue by fire** [pinterest/riffed#28]
Since the server I'm using requires the definition of:

`Type "i8" has not been defined.`

Can you check if Riffed works with thrift master?

Is there any other option I can take?

**Comment by scohen** [comment]
@fire, Thrift master is basically 0.10, we have a host of improvements that will take advantage of it on the this branch: https://github.com/pinterest/riffed/tree/rift_1_5_0. 
We're actively pushing the thrift community to release 0.10 asap.

Because of the improvements, Riffed works differently (and better) than the present version. You should check it out. I don't see any issue with `:i8` specifically. Riffed falls back on what the Erlang version uses for types and it should "just work" in this case.

**Comment by fire** [comment]
After switching to rift_1_5_0, the riffed part just works!
